spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  application:
    name: BasketService

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3309/basketservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/




server:
  port: 8040

logging:
  level:
    org:
      springframework:
        security=DEBUG: