# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: authservice-deployment
serviceName: authservice
appLabel: authservice
appName: authservice

replicaCount: 2

image:
  repository: tarikhamarat/authservice
  tag: s17

containerPort: 8099

service:
  type: ClusterIP
  port: 8099
  targetPort: 8099

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
