global:
  configMapName: greenprojectprod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  discoveryServerURL: "http://spring-cloud-kubernetes-discoveryserver:80/"
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
 